<?php
namespace Wkii\Yii2Rbac\base;

use Wkii\Yii2Rbac\behaviors\RbacBehavior;
use yii\filters\AccessControl;

/**
 * Created by PhpStorm.
 * User: chaitao
 * Date: 16/3/3
 * Time: 13:48
 */
class Controller extends \yii\web\Controller
{
    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['rbac'] = [
            'class' => RbacBehavior::className()
        ];
//        $behaviors['access'] = [
//            'class' => AccessControl::className(),
//            'rules' => [
//                [
//                    'allow' => true,
//                    'roles' => ['@']
//                ]
//            ]
//        ];
        return $behaviors;
    }
}